export { default as Homepage } from './Home'
export { default as Loginpage } from './Login'
export { default as Dashboard } from './Dashboard'
export { default as Register } from './Register'
export { default as Doctor } from './Doctor'
export { default as DoctorLogin } from './DoctorLogin'